spring:
  config:
    activate:
      on-profile: prod

app:
  media:
    object-prefix: ${COS_OBJECT_PREFIX:prod}
    cos:
      enabled: true

server:
  shutdown: graceful
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    root: INFO
